### ISSUE TITLE
Are you continue writing this tutorials?

### ISSUE THREAD

**Issue by un4ckn0wl3z** [RedYu/Plants-vs-Zombies#1]
I follow up your tutorial from part 1 to 4... but I can't found the 5th part. Are you continue this series? if not it's very sad :(

**Comment by RedYu** [comment]
Hey, I've written the 5th and 6th parts, but probably I didn't update the subject on the forum. I'll try to find it and update it. You can ask me if you don't understand something.

**Comment by un4ckn0wl3z** [comment]
> Hey, I've written the 5th and 6th parts, but probably I didn't update the subject on the forum. I'll try to find it and update it. You can ask me if you don't understand something.

Thank for reply. If it already readable. Can you send the link of your article for 5th and 6th part ? your article was very impressive.

**Comment by RedYu** [comment]
https://forum.zone-game.info/showthread.php?t=41132

**Comment by un4ckn0wl3z** [comment]
> https://forum.zone-game.info/showthread.php?t=41132

thanks bro. and how about part 6 ?

**Comment by RedYu** [comment]
I can’t find the archive of 6th part.

**Comment by un4ckn0wl3z** [comment]
OK bro, btw Thanks for tutorial :)
